refactor setup scripts

diff --git a/cmake/setup.sh.in b/cmake/setup.sh.in
--- a/cmake/setup.sh.in
+++ b/cmake/setup.sh.in
@@ -1,8 +1,39 @@
-# set up environment variables
-# the ${VAR:+:} part adds a double colon only if VAR is not empty
-export PATH="@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_BINDIR@${PATH:+:}${PATH}"
-export LD_LIBRARY_PATH="@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@${LD_LIBRARY_PATH:+:}${LD_LIBRARY_PATH}"
-export DYLD_LIBRARY_PATH="@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@${DYLD_LIBRARY_PATH:+:}${DYLD_LIBRARY_PATH}"
+# This file is part of the ACTS project.
+#
+# Copyright (C) 2016 CERN for the benefit of the ACTS project
+#
+# This Source Code Form is subject to the terms of the Mozilla Public
+# License, v. 2.0. If a copy of the MPL was not distributed with this
+# file, You can obtain one at https://mozilla.org/MPL/2.0/.
 
-# Acts project source directory
+# This script sets up the ACTS environment without dependencies in a somewhat robust way.
+
+if [ -n "${ZSH_VERSION:-}" ]; then
+    script_dir=${0:a:h}
+elif [ -n "${BASH_VERSION:-}" ]; then
+    script_dir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+else
+    # If the current shell is not ZSH or Bash, we can't guarantee that the
+    # script will work, so we throw an error.
+    echo "ERROR:   neither ZSH nor Bash was detected, other shells are not supported. The environment has not been modified."
+    exit 1
+fi
+
+# make ACTS binaries available
+# detect if we are installed as there is no lib subdirectory
+if [ ! -d "$script_dir/lib" ] && [ ! -d "$script_dir/lib64" ]; then
+    script_dir=$( cd -- "$script_dir" &> /dev/null && cd .. &> /dev/null && pwd )
+
+    export PATH="$script_dir/bin:${PATH}"
+    export LD_LIBRARY_PATH="$script_dir/lib:${LD_LIBRARY_PATH}"
+    export DYLD_LIBRARY_PATH="$script_dir/lib:${DYLD_LIBRARY_PATH}"
+else
+    # the ${VAR:+:} part adds a double colon only if VAR is not empty
+    export PATH="@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_BINDIR@${PATH:+:}${PATH}"
+    export LD_LIBRARY_PATH="@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@${LD_LIBRARY_PATH:+:}${LD_LIBRARY_PATH}"
+    export DYLD_LIBRARY_PATH="@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@${DYLD_LIBRARY_PATH:+:}${DYLD_LIBRARY_PATH}"
+fi
+
+# ACTS project source directory
 export ACTS_SOURCE_DIR="@PROJECT_SOURCE_DIR@"
+export ODD_SOURCE_DIR="@PROJECT_SOURCE_DIR@/thirdparty/OpenDataDetector"
